import type {Metadata} from "next";

import Link from "next/link";

import {CartProvider} from "./CartContext";

import "./globals.css";

export const metadata: Metadata = {
  title: "cart-test",
  description: "Generated by appncy",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="es">
      <body className="container m-auto grid min-h-screen grid-rows-[auto_1fr_auto] gap-8 px-4">
        <CartProvider>
          <header className="flex gap-10 text-xl leading-[4rem] font-bold">
            <Link href="/">cart-test</Link>
            <Link className="underline" href="/register">
              Register
            </Link>
            <Link className="underline" href="/login">
              Login
            </Link>
          </header>
          {children}
          <footer className="text-center leading-[4rem] opacity-70">cart-test</footer>
        </CartProvider>
      </body>
    </html>
  );
}
